fix #369
ffftp/ffftp pull request #380
Opened 2022-08-16 17:24 UTC by Kurukuru-Shisa

引数のRemoteFile、Oldの最後尾要素にはファイル名が含まれているため、
指定したファイル名のディレクトリが作成されていました。
remove_filename()でファイル名を取り除き、ディレクトリが作成されないように修正しました。

2022-08-16 21:10 UTC, sayurin requested changes
PRありがとうございます。コードを一部改善してほしいかなと。

2022-08-16 21:19 UTC, sayurin requested changes

2022-08-16 21:19 UTC, sayurin commented on ftpproc.cpp
> +	RemotePath.remove_filename();
`auto const RemotePath = RemoteFile.parent_path()` で済みますか？ `OldPath` の方も。この方法なら、変更を加えないので`const`も付けられますし。

2022-08-16 21:19 UTC, sayurin commented on ftpproc.cpp
> +
あ、無駄な空行も減らしたいです。

2022-08-17 01:01 UTC, Kurukuru-Shisa commented on ftpproc.cpp
> +	RemotePath.remove_filename();
レビューありがとうございます。コード修正しました。
`parent_path()`を使用した方がコードがわかりやすいですね。動作も問題ありませんでした。

2022-08-17 01:07 UTC, Kurukuru-Shisa commented on ftpproc.cpp
> +
空行を削除しました。

2023-05-04 23:46 UTC, sayurin approved these changes

2023-05-04 23:46 UTC, merged